platform :ios, '8.0'
use_frameworks!

target 'SmartLight' do
    pod "MagicalRecord"
    pod 'Alamofire'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'R.swift',:git=>'https://github.com/mac-cain13/R.swift.git'
    pod 'YYKit'
    pod 'CocoaLumberjack/Swift'
    pod 'RealmSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end